export default StorageNames = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  CONFIRM_JOB: "CONFIRM_JOB",
  OFFICER_PROFILE: "OFFICER_PROFILE",
  INITIAL_APP: "INITIAL_APP",
  UPDATE_ALL_PROFILE: "UPDATE_ALL_PROFILE",
  TRUE: "TRUE",
  FASLE: "FASLE",
};
