const ScreenNames = {
  DEMO: "DEMO",
  FIRST: "FIRST",

  // SPLASH
  SPLASH: "SPLASH",
  MAIN_NAVIGATOR: "MAIN_NAVIGATOR",
  BOTTOM_TAB_NAVIGATOR: "BOTTOM_TAB_NAVIGATOR",
  // End Splash

  // Authentication
  ABOUT: "ABOUT",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  AUTH_HOME: "AUTH_HOME",
  ACTIVE_ACCOUNT: "ACTIVE_ACCOUNT",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  CONFIRM_OTP_PASSWORD: "CONFIRM_OTP_PASSWORD",

  // End Authentication
  HOME: "HOME",
  EMAIL: "EMAIL",
  ACCOUNT: "ACCOUNT",
  BENEFITS: "BENEFITS",
  //
  UPDATE_PROFILE: "UPDATE_PROFILE",
  ADD_PROFILE: "ADD_PROFILE",

  // Get a job
  TAKE_JOB: "TAKE_JOB",
  PAYMENT: "PAYMENT",
  CASH: "CASH",
  BOOKING_TIME: "BOOKING_TIME",
};

export default ScreenNames;
